import Head from 'next/head'

export default function head() {
    return (
        <Head>
            <title>JennyHouse Blog</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/jh.ico" />
        </Head>
    )   
}